<?php

namespace Project\LineOfWorkBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    
    public function random($type){
        $qb = $this->createQueryBuilder('f')
                ->select('f.id')
                ->where('f.article_type =:type')
                ->setParameter('type',$type)
                ->getQuery();
        
        $array = $qb->getScalarResult();
        //if($array===null){
        //    return null;
        //}
        $feedback = $array[array_rand($array)];
        $id = $feedback['id'];
        //$id = $array[array_rand($array)];
        
        $query = $this->createQueryBuilder('f')
                ->where('f.id =:id')
                ->setParameter('id',$id);
        $result = $query->getQuery();
        
       try{
            $res = $result->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            $res = null;
        }
        return $res; 
        
        
    }
    
}
