Project\LineOfWorkBundle\Entity\Category:
    type: entity
    repositoryClass: Project\LineOfWorkBundle\Repository\CategoryRepository
    table: category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
    oneToMany:
        jobs:
            targetEntity: Job
            mappedBy: category
    lifecycleCallbacks:
        prePersist: [setSlugValue]
        preUpdate: [setSlugValue]