Project\LineOfWorkBundle\Entity\Phrase:
    type: entity
    name: phrase
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        main_header:
            type: string
            length: 10
        medium_header:
            type: string
            length: 50
        medium_paragraph:
            type: string
            length: 50
        bottom_paragraph:
            type: string
            length: 50
