imports:
    - { resource: parameters.yml }
    #- { resource: parameters_test.yml }
    - { resource: security.yml }
    - { resource: @ProjectLineOfWorkBundle/Resources/config/config.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - "ProjectLineOfWorkBundle:Form:fields.html.twig"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ProjectLineOfWorkBundle, SakyHankOfficialSiteBundle ]
    #java: /usr/bin/java
    node: "C:\\node\\node.exe"
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "C:\\Users\\SakyHank\\AppData\\Roaming\\npm\\bin\\uglifyjs"
        uglifycss:
            bin: "C:\\Users\\SakyHank\\AppData\\Roaming\\npm\\bin\\uglifycss"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js
            
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css
            
            filters: [cssrewrite]
        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
            
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    spool:     { type: memory }
    encryption: ssl
    auth_mode:  login
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Project\LineOfWorkBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        #email:
            #template: ProjectLineOfWorkBundle:User:confirmation.email.html.twig
        confirmation:
            enabled:    true
            from_email:
                address:        registration@lineofwork.com
                sender_name:    ProjectLineOfWork - Registration
    resetting:
        email:
            from_email:
                address:    resetting@lineofwork.com
                sender_name:    ProjectLineOfWork - Resetting Password

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.rss:

sonata_admin:
    title:  Project LineOfWork
    
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            client: default
            types:
                job:
                    mappings:
                        id: ~
                        position: { analyzer: snowball }
                        category:                           
                        location: { analyzer: snowball }
                        company: { analyzer: snowball }
                    persistence:
                        driver: orm
                        model: Project\LineOfWorkBundle\Entity\Job
                        provider: ~
                        listener: ~
                        finder: ~
                        repository: Project\LineOfWorkBundle\Repository\SearchRepository
