saky_hank_official_site:
    resource: "@SakyHankOfficialSiteBundle/Resources/config/routing.yml"
    prefix:   /

project_line_of_work:
    resource: "@ProjectLineOfWorkBundle/Resources/config/routing.yml"
    prefix:   /

