saky_hank_official_site:
    resource: "@SakyHankOfficialSiteBundle/Resources/config/routing.yml"
    prefix:   /ddd

project_line_of_work:
    resource: "@ProjectLineOfWorkBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"